### ISSUE TITLE
Problems with two-factor authentication

### ISSUE THREAD

**Issue by schwippe** [paypal/PayPal-iOS-SDK#320]
We are using the newest iOS SDK version in our app. When trying to log in with an account that has two-factor authentication enabled, we always get the following error message:
"System error (2fa_required). Please try again later." 
Are we doing something wrong?

These are our backend dependencies:
<dependency>
 <groupId>com.paypal.sdk</groupId>
 <artifactId>rest-api-sdk</artifactId>
 <version>0.11.0</version>
</dependency>

<dependency>
 <groupId>com.paypal.sdk</groupId>
 <artifactId>paypal-core</artifactId>
 <version>1.6.8</version>
</dependency>

**Comment by schwippe** [comment]
We also use the Android SDK and have no issues with the two-factor authentication.

**Comment by zerodiff** [comment]
FWIW, we also have a user who was having trouble with two-factor auth, and we're using the 2.9.0 version of the SDK. I'm continuing to investigate, and I'll update if I can reproduce the same issue.

**Comment by zerodiff** [comment]
FWIW, I tried the latest version, and it didn't even send me the text for the one-time password, it just gave me the error that @schwippe got. On 2.9.0, it sends the code, you enter the code, and then nothing (except a log message in XCode when run through the simulator).

**Comment by schwippe** [comment]
Hi @zerodiff, thanks a lot for your comments. So it seems to be a problem within the SDK or with the PayPal backend.

**Comment by zerodiff** [comment]
@schwippe I'd assume it's a problem with the PayPal iOS SDK because you noted that it works on Android (unless they use different backends, which I think is unlikely). I've opened a case with PayPal, and I'll keep any updates posted.

**Comment by md42** [comment]
In case anybody is talking to payPal support I created a ticket 150901-000111 on 1.9.2015 for same problem @schwippe has at Supportsite https://www.paypal-techsupport.com/ but did not yet get an answer

**Comment by tomwhipple** [comment]
Two factor message delivery has been experiencing some problems over the past few days. I believe this has now been resolved.

**Comment by zerodiff** [comment]
@tomwhipple I tried again, and I still get the error message and after that no prompt to send or enter the auth code for the latest 2.11.4 SDK.

**Comment by tomwhipple** [comment]
Yep, confirmed. I see the 2FA message, but there's definitely some odd behavior. We'll take a look.

**Comment by ladylo50bear** [comment]
Close this website from my account

**Comment by bluk** [comment]
Hi, can you try release [2.12.1](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.12.1) for a fix for the 2FA flow. Thanks!

**Comment by zerodiff** [comment]
@bluk I'm getting a compile error:
```
duplicate symbol _llvm.cmdline in:
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskUtility.o)
duplicate symbol _llvm.embedded.module in:
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskUtility.o)
duplicate symbol _llvm.cmdline in:
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskConfiguration.o)
duplicate symbol _llvm.embedded.module in:
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskConfiguration.o)
duplicate symbol _llvm.cmdline in:
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskLinkerID.o)
duplicate symbol _llvm.embedded.module in:
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskLinkerID.o)
duplicate symbol _llvm.cmdline in:
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskComponent.o)
duplicate symbol _llvm.embedded.module in:
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskComponent.o)
ld: 8 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is in Xcode Version 6.4 (6E35b).

**Comment by ladylo50bear** [comment]
Remove 320 website

**Comment by ladylo50bear** [comment]
Remove 320 website

**Comment by bluk** [comment]
@zerodiff Thanks for the quick try. Investigating the new issue. There seem to be mixed results with deleting the `DerivedData` which may help, but it may also be a general Xcode 7 build issue with Xcode 6.4 projects.

**Comment by zerodiff** [comment]
@bluk I was able to build it with Xcode 7, and I get all the way through to entering the code that was SMS'd, but there's not button or "Done" on the keyboard to actually submit the code to auth. So, almost there, but still can't fully auth. This was a problem on 2.9.0 also, as mentioned above.

Thanks for continuing to look into this.

**Comment by bluk** [comment]
@zerodiff Still looking into the Xcode 6.4 vs. Xcode 7 issue but glad you got it to link in Xcode 7. So when you get to the 2-Factor Authentication view, you do not see the "Log In" button in the upper right?

![img_0074](https://cloud.githubusercontent.com/assets/94150/9882893/e5eef562-5b8b-11e5-8425-2aef8a989f18.PNG)

**Comment by zerodiff** [comment]
Correct, I do not see the "Log In" button (although you may want to add another button that might look more obvious around where there user is entering the code). 

![img_0161](https://cloud.githubusercontent.com/assets/3653615/9883230/8c5c6bca-5b9e-11e5-80fd-a065783fed6e.PNG)

**Comment by zerodiff** [comment]
One more from someone else's phone to make sure I'm not hallucinating:

![img_1396](https://cloud.githubusercontent.com/assets/3653615/9883496/0a155940-5ba0-11e5-8100-e6c6e56760ee.PNG)

**Comment by zerodiff** [comment]
Nevermind... I found the source of the "missing" buttons. We had:
```
    UIBarButtonItem *barButtonAppearance = [UIBarButtonItem appearance];
    [barButtonAppearance setTintColor:[UIColor whiteColor]];
```
Not knowing exactly how the `PayPalPaymentViewController` is constructed, it took me a while to figure out. Thanks for the help. I'm able to log in with two-factor auth now.

**Comment by ladylo50bear** [comment]
On Sep 14, 2015 4:35 PM, "Erik" <notifications@github.com> wrote:
>
> @bluk I'm getting a compile error:
>
> duplicate symbol _llvm.cmdline in:
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskUtility.o)
> duplicate symbol _llvm.embedded.module in:
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskUtility.o)
> duplicate symbol _llvm.cmdline in:
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskConfiguration.o)
> duplicate symbol _llvm.embedded.module in:
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskConfiguration.o)
> duplicate symbol _llvm.cmdline in:
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskLinkerID.o)
> duplicate symbol _llvm.embedded.module in:
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskLinkerID.o)
> duplicate symbol _llvm.cmdline in:
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskComponent.o)
> duplicate symbol _llvm.embedded.module in:
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
>
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskComponent.o)
> ld: 8 duplicate symbols for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see
invocation)

**Comment by tomwhipple** [comment]
2.12.x requires XCode 7 or newer. This should go away if you upgrade.

**Comment by ladylo50bear** [comment]
Don't know what to

**Comment by ladylo50bear** [comment]
Don't know what this website is

**Comment by ladylo50bear** [comment]
On Sep 18, 2015 10:46 AM, "Lorraine Espinosa" <loespinosa95@gmail.com>
wrote:
>
>
> On Sep 14, 2015 4:35 PM, "Erik" <notifications@github.com> wrote:
> >
> > @bluk I'm getting a compile error:
> >
> > duplicate symbol _llvm.cmdline in:
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskUtility.o)
> > duplicate symbol _llvm.embedded.module in:
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskUtility.o)
> > duplicate symbol _llvm.cmdline in:
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskConfiguration.o)
> > duplicate symbol _llvm.embedded.module in:
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskConfiguration.o)
> > duplicate symbol _llvm.cmdline in:
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskLinkerID.o)
> > duplicate symbol _llvm.embedded.module in:
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskLinkerID.o)
> > duplicate symbol _llvm.cmdline in:
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskComponent.o)
> > duplicate symbol _llvm.embedded.module in:
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
> >
ios7/Libraries/PayPal-iOS-SDK-2.12.1/PayPalMobile/libPayPalMobile.a(PPRiskComponent.o)
> > ld: 8 duplicate symbols for architecture i386
> > clang: error: linker command failed with exit code 1 (use -v to see
invocation)

**Comment by bluk** [comment]
It seems the original issue with 2-factor authentication is fixed so I'll close this issue. Regarding the Xcode 6.4 vs. 7, if there's a solution it will be provided to fix issue #327.

**Comment by ladylo50bear** [comment]
Problems with two-factor authentication · Issue #320 ·
paypal/PayPal-iOS-SDK
https://github.com/paypal/PayPal-iOS-SDK/issues/320#issuecomment-140218663
(Share from CM Browser)

**Comment by schwippe** [comment]
The latest version of SDK in combination with Xcode 7 works fine. Thanks to all of you.

**Comment by ladylo50bear** [comment]
On Sep 20, 2015 1:59 AM, "schwippe" <notifications@github.com> wrote:
>
> The latest version of SDK in combination with Xcode 7 works fine. Thanks
to all of you.

**Comment by ladylo50bear** [comment]
Release 2 12 1

**Comment by asifhabib** [comment]
The biggest problem moving to new environment is that every one is not ready yet. 
I restarted my computer and it stop working on Xcode 6.4 with same error. I moved to Xcode 7 for paypal, and GooglePlus framework is not ready for Xcode 7. (headbang)
Is there any old SDK which I can run on Xcode 6.4. I have to just made simple transaction.

**Comment by ladylo50bear** [comment]
Have a question about using DocuSign? Get answers at the DocuSign Support
Center
https://support.docusign.com/articles/Why-can-t-I-log-into-the-Chrome-Extension

**Comment by ladylo50bear** [comment]
Close

**Comment by tomwhipple** [comment]
I'm locking this thread due to a number of spam posts... Please open new issues if need be.
