### ISSUE TITLE
Duplicate Symbols when using in a static lib

### ISSUE THREAD

**Issue by marchbold** [paypal/PayPal-iOS-SDK#300]
Hi,

I'm trying to use the PayPal SDK in a library that we use in our applications. I include the PayPal SDK (headers + libPayPalMobile.a) in our library, and linking the libPayPalMobile.a with our target output static lib. 

This procedure worked fine in the past (v2.9.0) however more recent version I'm encountering duplicate symbol errors, as listed below.

I have also tried not linking the libPayPalMobile.a library directly in our library target but packaging both with our application and this results in the same error.

I have read other issues reported here about this that were resolved by using a more recent Xcode. I am currently using the most recent: 6.4 

Any ideas?

```
duplicate symbol l034 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PayPalPaymentViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentMethodCell.o)
duplicate symbol l035 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PayPalPaymentViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentMethodCell.o)
duplicate symbol l036 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentMethodCell.o)
duplicate symbol l037 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentMethodCell.o)
duplicate symbol l026 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPDeviceCheckViewController.o)
duplicate symbol l027 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPDeviceCheckViewController.o)
duplicate symbol l028 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPDeviceCheckViewController.o)
duplicate symbol l033 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentMethodCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
duplicate symbol l034 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PayPalPaymentViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
duplicate symbol l035 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PayPalPaymentViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
duplicate symbol l036 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
duplicate symbol l037 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
duplicate symbol l038 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentMethodCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
duplicate symbol l034 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PayPalPaymentViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPServiceRequest.o)
duplicate symbol l026 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l027 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l028 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l029 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l030 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l031 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPSelectPayMethodViewControllerIOS6.o)
duplicate symbol l023 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPBaseViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PayPalProfileSharingViewController.o)
duplicate symbol l016 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentAttributeSelectionCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
duplicate symbol l017 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentAttributeSelectionCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
duplicate symbol l005 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPTableViewCellDefaults.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l007 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAHeaderTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l008 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAHeaderTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l009 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAHeaderTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l010 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPCreditCardMethodCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l011 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPCreditCardMethodCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l012 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAHeaderTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l013 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAHeaderTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l014 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l015 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l016 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentAttributeSelectionCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l017 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentAttributeSelectionCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l018 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l019 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l020 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPAnalyticsTracker.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(UIImage+ImageEffects.o)
duplicate symbol l099 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPAuthConsentViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraAnalyticsTracker.o)
duplicate symbol l016 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentAttributeSelectionCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASecurityCodeTableViewCell.o)
duplicate symbol l017 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentAttributeSelectionCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASecurityCodeTableViewCell.o)
duplicate symbol l018 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASecurityCodeTableViewCell.o)
duplicate symbol l019 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASecurityCodeTableViewCell.o)
duplicate symbol l020 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPAnalyticsTracker.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASecurityCodeTableViewCell.o)
duplicate symbol l018 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPSelectPayMethodViewControllerIOS7.o)
duplicate symbol l019 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPSelectPayMethodViewControllerIOS7.o)
duplicate symbol l020 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPAnalyticsTracker.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPSelectPayMethodViewControllerIOS7.o)
duplicate symbol l010 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPCreditCardMethodCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAHeaderTableViewCell.o)
duplicate symbol l011 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPCreditCardMethodCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAHeaderTableViewCell.o)
duplicate symbol l022 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PayPalProfileSharingViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PayPalFuturePaymentViewController.o)
duplicate symbol l035 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PayPalPaymentViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(FPTIData.o)
duplicate symbol l036 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAViewController.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(FPTIData.o)
duplicate symbol l033 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentMethodCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPMultipleFieldTableViewCell.o)
duplicate symbol l003 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPTableViewCellDefaults.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPViewShake.o)
duplicate symbol l004 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPTableViewCellDefaults.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPViewShake.o)
duplicate symbol l005 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPTableViewCellDefaults.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPViewShake.o)
duplicate symbol l030 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPZebraUI.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPHTML.o)
duplicate symbol l013 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FAHeaderTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPModalActivityIndicator.o)
duplicate symbol l014 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPModalActivityIndicator.o)
duplicate symbol l015 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPModalActivityIndicator.o)
duplicate symbol l016 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentAttributeSelectionCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPModalActivityIndicator.o)
duplicate symbol l017 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPPaymentAttributeSelectionCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPModalActivityIndicator.o)
duplicate symbol l018 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPModalActivityIndicator.o)
duplicate symbol l019 in:
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PP2FASMSTableViewCell.o)
    /var/folders/_f/50mnsmrx5hn4g89kdz94vvk40000gn/T/47c0989a-fa4d-4639-8bd0-aaa950938f68/libcom.distriqt.PayPalSDK.a(PPModalActivityIndicator.o)
```

**Comment by tomwhipple** [comment]
Are you using any other libraries in your app? For example, [Braintree iOS](https://github.com/braintree/braintree_ios) includes the PayPal MSDK.

You also might make sure that the old version of the library isn't being cached or duplicated somewhere.

**Comment by marchbold** [comment]
No other libraries in the app that could contain the PayPal SDK. 
And I've double checked that there's only the one version of the SDK included.

**Comment by tomwhipple** [comment]
The only thing that makes sense here is that the SDK is somehow being linked twice. The only thing I can suggest would be to open the sample app project and compare build settings line by line. 

(And even then, triple check... I made a mistake the other day where I was looking at the build settings for a test project and not my main app.)

**Comment by ppmtscory** [comment]
@marchbold were you able to get this resolved?

**Comment by marchbold** [comment]
No I haven't been able to resolve it, I'm still using the older SDK.

@tomwhipple I have triple checked the build process and I'm certain it's not being linked twice and this does not explain why it worked with the older SDK.

**Comment by MattFoley** [comment]
I updated to 2.11.5 today from 2.10.1, and am also building a static library on Xcode 6.4. It was working fine on 2.10.1, but is now failing on 2.11.5.

**Comment by braebot** [comment]
PayPal Mobile SDKs are Deprecated. The APIs powering them will remain operational long enough for merchants to migrate, but the SDKs themselves will no longer be updated. Please use [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct) in [supported countries](https://www.braintreepayments.com/country-selection). In other countries, use [Express Checkout](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) and choose the Braintree SDK integration option.
