### ISSUE TITLE
Duplicate Symbols Errors

### ISSUE THREAD

**Issue by asifhabib** [paypal/PayPal-iOS-SDK#327]
Hi, I added the SDK, followed all the instructions and compiled, had errors mentioned bellow. Then I just compiled the Sample code, same error. Running on  Xcode is 6.4. While same code was able to run on Xcode 7.0 beta 5. 
Now going to download Xcode 7, any solution before Xcode 7 is downloaded. Thanks.  
duplicate symbol _llvm.cmdline in:
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskUtility.o)
duplicate symbol _llvm.embedded.module in:
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskUtility.o)
duplicate symbol _llvm.cmdline in:
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskConfiguration.o)
duplicate symbol _llvm.embedded.module in:
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskConfiguration.o)
duplicate symbol _llvm.cmdline in:
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskLinkerID.o)
duplicate symbol _llvm.embedded.module in:
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskLinkerID.o)
duplicate symbol _llvm.cmdline in:
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskComponent.o)
duplicate symbol _llvm.embedded.module in:
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskDeviceData.o)
    /Users/asifhabib/Downloads/PayPal-iOS-SDK-6da680505fd8110a12d027b379f128a960ce349e/PayPalMobile/libPayPalMobile.a(PPRiskComponent.o)
ld: 8 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bluk** [comment]
I recommend upgrading to Xcode 7. Unfortunately, there is a general issue if there's any compiled Bitcode enabled code within the library will cause Xcode 6.4 or lower to not link correctly. I'll leave this issue open as I'm still investigating if there's any other way but it is better to upgrade to Xcode 7 through the App Store.

**Comment by asifhabib** [comment]
I was not planning to move to Xcode 7 right now! But I think I have to.

**Comment by asifhabib** [comment]
The biggest problem moving to new environment is that every one is not ready yet. 
I restarted my computer and it stop working on Xcode 6.4.1 with same error. I moved to Xcode 7 for paypal, and GooglePlus framework is not ready for Xcode 7. (headbang)
Is there any old SDK which I can run on Xcode 6.4.1. I have to just made simple transaction.

**Comment by tomwhipple** [comment]
@bluk tells me he will release an update to SDK 2.11 with a fix #320 very soon, built with the older tools.

**Comment by bluk** [comment]
Hi, please try release [2.11.5](https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.11.5) which was built without Bitcode enabled. It has the latest fixes but does not have Bitcode enabled at all in the static library which should fix the duplicate symbol issue.
